[package]
name = "use-cases-notifications"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
application-ports.workspace = true
contracts.workspace = true
notification-domain.workspace = true
profile-platform-primitives.workspace = true

[lints]
workspace = true
