[package]
name = "browser-profile-control-plane-worker"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cloudflare-adapters.workspace = true
control-plane-contract = { path = "../../crates/control-plane-contract" }
wasm-bindgen.workspace = true
worker.workspace = true

[lints]
workspace = true
