#![forbid(unsafe_code)]

pub mod access_identity;
pub mod access_webcrypto;
pub mod contact_keyring;
pub mod contact_lookup;
pub mod contact_protection;
pub mod coordinator_ingress;
pub mod d1_catalog;
pub mod d1_client_merge;
pub mod d1_client_persistence;
pub mod d1_client_registry;
pub mod d1_clients;
mod d1_command_identity;
pub mod d1_contact_query;
pub mod d1_global_query;
pub mod d1_governed_commands;
pub mod d1_idempotency;
pub mod d1_identity_acl;
pub mod d1_identity_ceremonies;
mod d1_identity_failure;
pub mod d1_identity_governance;
pub mod d1_identity_queries;
pub mod d1_integration_events;
pub mod d1_invitation_acceptance;
pub mod d1_mailbox_bindings;
pub mod d1_mailbox_jobs;
pub mod d1_mailboxes;
pub mod d1_notification_operations;
pub mod d1_notifications;
pub mod d1_profile_application;
pub mod d1_profile_coordinator;
pub mod d1_profile_generation_application;
pub mod d1_profile_generations;
pub mod d1_profiles;
pub mod d1_query;
pub mod fake_mail_query;
pub mod integration_event_queue;
pub mod mailbox_provider;
pub mod profile_coordinator;

pub use mailbox_domain::MailboxProvider;
