[package]
name = "use-cases-mailboxes"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
application-ports.workspace = true
identity-access-domain.workspace = true
mailbox-domain.workspace = true
profile-platform-primitives.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
